export const initialItems = [
  {
    id: "item-1",
    name: "Chips",
    image: "./assets/chips.png",
    width: 40,
    height: 80,
    bgColor: "#f5deb3",
    description: "Crispy potato chips - perfect for snacking anytime. Made with premium potatoes and seasoned to perfection.",
    stackable: true,
    quantity: 1,
    brand: "Lay's",
    price: "$2.99"
  },
  {
    id: "item-2",
    name: "Nachos",
    image: "/images/nachos.png",
    width: 60,
    height: 100,
    bgColor: "#f4a460",
    description: "Crunchy tortilla chips ideal for dipping. Great with salsa, cheese, or guacamole.",
    stackable: true,
    quantity: 1,
    brand: "Tostitos",
    price: "$3.49"
  },
  {
    id: "item-3",
    name: "Nuts",
    image: "/images/nuts.png",
    width: 40,
    height: 70,
    bgColor: "#deb887",
    description: "Mixed nuts containing almonds, cashews, and peanuts. A healthy snack option rich in protein.",
    stackable: true,
    quantity: 1,
    brand: "Planters",
    price: "$4.99"
  },
  {
    id: "item-4",
    name: "Biscuits",
    image: "/images/biscuits.png",
    width: 100,
    height: 30,
    bgColor: "#ffe4c4",
    description: "Sweet and crunchy biscuits made with real butter. Perfect with tea or coffee.",
    stackable: true,
    quantity: 1,
    brand: "Oreo",
    price: "$3.29"
  },
  {
    id: "item-5",
    name: "Candy",
    image: "/images/candy.png",
    width: 40,
    height: 40,
    bgColor: "#ffb6c1",
    description: "Assorted colorful candies with fruity flavors. A delightful treat for all ages.",
    stackable: true,
    quantity: 1,
    brand: "Haribo",
    price: "$1.99"
  },
  {
    id: "item-6",
    name: "Soda",
    image: "/images/soda.png",
    width: 45,
    height: 70,
    bgColor: "#e0f7fa",
    description: "Refreshing carbonated soft drink with a crisp, clean taste. Best served chilled.",
    stackable: false,
    quantity: 1,
    brand: "Sprite",
    price: "$1.79"
  },
  {
    id: "item-7",
    name: "Juice",
    image: "/images/juice.png",
    width: 50,
    height: 100,
    bgColor: "#ffcc80",
    description: "100% natural fruit juice packed with vitamins. No artificial colors or preservatives.",
    stackable: false,
    quantity: 1,
    brand: "Tropicana",
    price: "$3.99"
  },
  {
    id: "item-8",
    name: "Cola",
    image: "/images/cola.png",
    width: 50,
    height: 120,
    bgColor: "#d32f2f",
    description: "Classic cola drink with the perfect balance of sweetness and fizz. An iconic refreshment.",
    stackable: false,
    quantity: 1,
    brand: "Coca-Cola",
    price: "$1.99"
  }
];